version: '3.8'

services:
  ad-service:
    build:
      context: ./src/ad/
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - AD_PORT=9090
      - FEATURE_FLAG_GRPC_SERVICE_ADDR=featureflagservice:50053
    depends_on:
      - featureflagservice

  product-catalog:
    build:
      context: ./src/product-catalog  
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - PRODUCT_CATALOG_PORT=8088

  recommendation-service:
    build:
      context: ./src/recommendation 
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - product-catalog

